### PR TITLE
Crud brokers

### LINKED ISSUE #9: User Story- Staff members can edit and delete brokers
TODO:
- [x] Create Broker Model
- [x] Add Broker DbSet
- [x] Create Broker Interface
- [x] Create Brokers Repository
- [x] Add transient services to Startup File
- [x] Add Some Brokers to the seed data
- [x] Add a view for seeing all brokers
- [x] Add controller for brokers
- [x] Add Authorization to limit deletion functionality to Staff only, not admin
- [x] Add a Migration when finished with broker model
- [ ] Add View Model for editing broker

### PR DESCRIPTION
**Pull request by JGarnick**
I did not add the view model for editing a broker. Not sure if its necessary yet. Everything else should be finished. Fixes #9

### CODE REVIEW

**Comment by JGarnick** [comment]
Authorization doesn't seem to be working yet, but its not working on any page so will have to look into it more

**Review by PatrickRBailey — CHANGES_REQUESTED** [review]
I think the route changes you made is preventing Login from loading the homepage on success.

**Comment by JGarnick** [comment]
I've made changes. Fixed what I believe the problem was and set homepage back to default page

**Review by PatrickRBailey — APPROVED** [review]

**Comment by PatrickRBailey** [comment]
Looks good! Edit and delete functionality is working

**Pull request merged**
